[package]
name = "tungsten_parser"
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
tungsten_utils.workspace = true
tungsten_ast.workspace = true
tungsten_lexer.workspace = true
tungsten_symbols.workspace = true
tungsten_context.workspace = true
thiserror.workspace = true
anyhow.workspace = true
